// <auto-generated />
using BreachedEmailsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BreachedEmailsApi.Migrations
{
    [DbContext(typeof(BreachedEmailContext))]
    [Migration("20201001124608_BreachedEmailsApiModels.BreachedEmailContext")]
    partial class BreachedEmailsApiModelsBreachedEmailContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BreachedEmailsApi.Models.BreachedEmail", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Email");

                    b.ToTable("BreachedEmails");

                    b.HasData(
                        new
                        {
                            Email = "email1@email.com"
                        },
                        new
                        {
                            Email = "email2@email.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
